### ISSUE TITLE
Generator: License Manager: The charset is invalid.

### ISSUE THREAD

**Issue by curtishall** [drazenbebic/license-manager-for-woocommerce#102]
I've tested on two different installs of Wordpress (separate systems...).  When I try to create a new generator I get this error:

License Manager: The charset is invalid.

Tested today with 2.2.0

**Comment by drazenbebic** [comment]
@curtishall 

Can you tell me what you typed into the "Character map" field?

**Comment by drazenbebic** [comment]
@curtishall 

Any update on this?

**Comment by drazenbebic** [comment]
Closed due to inactivity.
