### ISSUE TITLE
License keys - Add your own expiration date to license keys

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#11]
When adding external license keys, it should be possible to define a set date for the license key expiration. This conflicts with the "valid for" field, so it should not be possible to define both.

**Comment by otakupahp** [comment]
Also, when you edit a license you can modify its validity but it does not update the expiration date. The validation date should be updated from the created date

**Comment by drazenbebic** [comment]
@otakupahp 

You are right. This will also be considered in the fix for this issue.

**Comment by drazenbebic** [comment]
Added in 540fe9b579030fe65fe9bd89ff91b6fa2f1e1807
