### ISSUE TITLE
License generated twice

### ISSUE THREAD

**Issue by otakupahp** [drazenbebic/license-manager-for-woocommerce#118]
**Describe the bug**
Some times, due to an unknown error, WooCommerce sets an order from processing to complete twice. That makes the plugin to generate 2 licenses.

**To Reproduce**
1. Created an order with a generator license for a product
2. Complete the order manually, that adds a license
3. Back the order "in processes" and then complete it again

**Expected behavior**
When a new license will be generated, a check must be done to avoid double license

**Comment by drazenbebic** [comment]
@otakupahp 

Does this still happen? I wasn't able to reproduce the issue. Do you maybe have any relevant PHP error logs?

**Comment by otakupahp** [comment]
I have not had the error again. I'll notify you if it happens again
