### ISSUE TITLE
A generic low level account for activations only

### ISSUE THREAD

**Issue by vrdriver** [drazenbebic/license-manager-for-woocommerce#119]
Hi, great program, but I've run in to a small problem, and I was wondering if you'd be able to make a fix.

I've just discovered that if a serial number is to be activated using a REST API key, that the user the API key is assigned to, must be an admin user in WP.  

As I'm planning on running my own serial numbers, I was hoping to have a low level generic account in WP, with basically no access to the backend, to be able to act as the registration account.  

I was planning on baking in this registration API key, so the user can automatically register their own software, because without I can't see any other way.

Is there another way to do this, where a user types in their code in their app, and clicks on register?

Unless you have plans to change the way the API keys work and assign specific roles to each key, rather than have a generic on/off for each of the APIs?

As you can imagine, the last thing I want to do is have multiple admin accounts on my WP shop site.

Cheers,
Steve

**Comment by vrdriver** [comment]
I have found the code I needed to comment out to solve my problem.  

Licences.php: @ lines 578-586
and
Licences.php: @ lines 798-806

You are welcome to close this job, or keep it open as a suggestion.

**Comment by drazenbebic** [comment]
Hello @vrdriver 

sorry for the late reply.

It's intended this way, but it could definitely be expanded upon.

Perhaps I could special plugin specific user role, something like "Licensing Agent". This role would only be used by the REST API. That way you could tie a specific integration to a WordPress user.

What do you think?

**Comment by vrdriver** [comment]
I think that would be a great idea. Unfortunately I'm not across many of the core WP APIs, but I think it would be a big help to have a "Licensing Agent" as you suggest, which would still need to be authenticated, but havethata lessor role (or no post edit  permissions) to the WP dataset.

**Comment by alex-drocks** [comment]
In my first impressions I was also expecting to create a dedicated wordpress user but I ended up using admin. Its not a big concern for me but I agree that it was and remains a logical first impression expectation. If its too much work maybe its not worth it though..

**Comment by drazenbebic** [comment]
@vrdriver @alex-drocks 

It's settled then. I'll mark this as a feature request for the upcoming 2.3.0 release. Shouldn't be too difficult.

**Comment by drazenbebic** [comment]
Added in acf66c695b4b4dbc6fbe4c5447834a0f55595565

Closed.
