### ISSUE TITLE
license is expired, but validation returns "success"

### ISSUE THREAD

**Issue by likemachines** [drazenbebic/license-manager-for-woocommerce#120]
we generated the license to check, what happens if the license is expired. now the expire date is over, the license is still returning "success" on validation check. 

We want to deactivate some of our plugin functions when the license expires. how to do this ? 
Is there a way to deactivate the license after the expire date automatically ?

**Comment by otakupahp** [comment]
I use the validation date to check if the license is valid. Maybe you could check the SDK I created for  my plugins: https://github.com/otakupahp/sdk-license-manager-for-woocommerce

**Comment by likemachines** [comment]
thank you !

**Comment by otakupahp** [comment]
It looks like you could solve the issue.
