### ISSUE TITLE
Generator - CRUD functions

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#123]
Add functions to create, update, delete, generators. As well as another function to utilize an existing generator to create license keys.

**Comment by risharde** [comment]
Hey @drazenbebic I need this one urgently, thank you for working on this plugin!

**Comment by drazenbebic** [comment]
Added in d0aa8185df6850872386c06a10a62a2c711c7e48

Closed.
