### ISSUE TITLE
License - Licenses not appearing in "My Account"

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#124]
Licenses are not always appearing in the "My Account" section. The culprit is the function which retrieves licenses for a customer. It needs to be rewritten to make use of the "user_id" column in the license's table.

**Comment by stefanmm** [comment]
Hi, will this be resolved anytime soon? I have the same problem. Thanks!

**Comment by drazenbebic** [comment]
@stefanmm 

yes, it will be done and included in the next update coming in January.

**Comment by drazenbebic** [comment]
Fixed in d437247069dad50e7643d9d94de9bb679c3c8b24
