### ISSUE TITLE
Bugs on REST API route definition on WordPress 5.5.0

### ISSUE THREAD

**Issue by conikal** [drazenbebic/license-manager-for-woocommerce#125]
**Describe the bug**
Have bug on api libs on wordpress 5.5.0. Hope you fix it soon. Thank you for your works.

**To Reproduce**
Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses/activate/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses/deactivate/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/licenses/validate/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/generators is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/generators/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/generators is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

Notice: register_rest_route was called incorrectly. The REST API route definition for lmfwc/v2/generators/(?P[\w-]+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/conikal.com/wp-includes/functions.php on line 5225

**Comment by drazenbebic** [comment]
@conikal Fixed in 77697f787fb168f0696e0788a8dedd15d49b743d

Which is also productive at the moment, go and update the plugin :)
