### ISSUE TITLE
WooCommerce Subscriptions Integration

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#13]
After receiving a development version of the plugin, it would be perfectly reasonable to see if it makes sense to add support and integrate the plugin into the WooCommerce Subscriptions plugin by Prospress.

- [x] Simple WooCommerce Subscriptions Support
- [x] Variable WooCommerce Susbcriptions Support
- [x] Subscriptions inside the Licenses table
- [x] Advanced product options (increase expiration date by subscription interval, or manually define the interval)

**Comment by srcmkr** [comment]
How would the integration look like?
For us, the integration already seems to work perfectly (keys are been generated upon renewal, integration in subscriptions *and* variations already working fine).
I might be able to support with a fully set-up shop + WC Subscriptions

**Comment by drazenbebic** [comment]
Hi @srcmkr,

I don't know yet to be honest. I have never used WC Subscriptions so I don't really know what to expect here. If you're saying that the plugin already works fine with it then perhaps this is not an issue at all.

**Comment by otakupahp** [comment]
I fact with I would like (with WC Subscriptions or any other) would be to have a license renewal. I the client rebuys the product (or buys the renewal subscription, then I can increase the expiration time by 365 days (or any other length) so the client does not have to add another code (especially useful when they have many sites running with the same plugin)

Could you image a way of automatically increase the expiration date?

**Comment by drazenbebic** [comment]
@otakupahp 

It must be possible, but I haven't had the time to check out this possible integration into WooCommerce Subscriptions to be honest.

As soon as I can, I will start developing this exact feature. When the Subscriptions plugin is active, you will have additional options for Subscription products (i.e. automatically renew expiration day after each subscription interval).

**Comment by otakupahp** [comment]
I will do a premium addon since it is not something needed for everyone. This way you will have an extra income for your great job with this plugin.
Also, that way you could better control the integration not only with this WC Subscriptions but with every future plugin

**Comment by drazenbebic** [comment]
@otakupahp 

The plugin is and will always remain a 100% free, so there will be no premium add-ons. This is functionality that will be part of the core code, and will automatically show if you have the WooCommerce Subscriptions plugin active.

I already have a bit of a plan regarding the WooCommerce Subscriptions plugin, I just need to... start developing :)

**Comment by DanielBakovic** [comment]
Congratulation on this great plugin. I would love to see a WC Subscription integration as @otakupahp suggested.

**Comment by drazenbebic** [comment]
Hello @DanielBakovic 

thank you! WC Subscriptions support is definitely coming, as I've already begun the development. I can't make any promises, but the next version (2.2.0) should include this feature.

**Comment by otakupahp** [comment]
To update this... Today I had my first renewal this is what happened:

1.- Client buys a TRIAL > got a CODE for 365 days. It would be great to give just a 30 days code (or the length of the trial) or use a secondary generator
2.- The renewal is done automatically > a new order is created and a new CODE for 365 days is generated. It would be great to just extend the old code

**Comment by otakupahp** [comment]
Congratulations for the new version, but you left this feature out :(

**Comment by drazenbebic** [comment]
@otakupahp 

Yeah, I really tried but I didn't move forward at a decent pace with this issue. I could use some help developing this feature. Would you be interested?

**Comment by otakupahp** [comment]
I can take a look, I was looking at your code and I could learn of trick or two.

**Comment by drazenbebic** [comment]
@otakupahp 

Great! Feel free to contact me via email if you have any questions (support@licensemanager.at). I will help you in any way I can.

**Comment by drazenbebic** [comment]
Hello @DanielBakovic , @otakupahp , @srcmkr  and @sebastienserre 

I have just made the first implementation of this feature. Here's the commit diff: https://github.com/drazenbebic/license-manager-for-woocommerce/commit/f32db809ba719d5d69b74b18bb91bef05ec6d2fe

Could someone please test the feature out and see if it works as intended?

It basically now extends the "ExpiresAt" field by the subscription duration. Please take a look and let me know if it needs adjustments.

**Comment by otakupahp** [comment]
Hey, @drazenbebic. Thanks for the update.

I looked at the code and I see that I have to update my products with a check to confirm that a license must be extended instead of regenerated, right?

If I do that in the products, will the current subscriptions be "updated" with the new feature? Or should I do anything else?

**Comment by drazenbebic** [comment]
@otakupahp 

correct, there is a new checkbox for simple subscription products. If ticked, every new renewal order will not generate a new license, but extend the expiration date of the original order license(s) by the subscription interval.

For example, if the subscription is billed every 2 months, then the expiration date will be set for 2 months from the date of the renewal order.

**Comment by otakupahp** [comment]
What about variable product subscriptions?

**Comment by drazenbebic** [comment]
@otakupahp working on those as well, should be available in the next commit.

**Comment by drazenbebic** [comment]
@otakupahp @DanielBakovic @srcmkr @sebastienserre 

I'm glad to let everyone know that the WC Subscription integration is almost done. Only thing left to do is to provide more options on the subscription products.

For now you can only activate a checkbox, and if it's activated then the plugin won't create a new license key. Instead, it will extend the expiration date of the existing license key by the subscription renewal period. I would like to introduce more options here. So far I thought of the following:

**Option 1: Dropdown**
- Issue a new license key on each subscription renewal
- Extend the existing license on each subscription renewal

**Option 2: Dropdown** (If Option 1 = "Extend the existing license on each subscription renewal") 
- Extend by the Subscription interval
- Extend by the amount of days defined in "Valid for"
- Extend by a custom interval

**Option 3: Number Input** (If Option 2 = "Extend by a custom interval")
A simple number input starting from 1. This will be used in combination with Option 4

**Option 4: Dropdown** (If Option 2 = "Extend by a custom interval")
- days
- weeks
- months
- years

What do you think?

**Comment by otakupahp** [comment]
I like it

**Comment by drazenbebic** [comment]
![image](https://user-images.githubusercontent.com/26099016/95026226-3342b880-0690-11eb-9045-68f18d3a21bd.png)

This is how it will look then.

**Comment by otakupahp** [comment]
Looks good, but I am not sure how it will look once you put it in the variables.

I use different generator for different variation, so I can not use a single "license manager" configuration. You should move the "License Manager" option inside the variation when you implement it.

Once again, great job

**Comment by drazenbebic** [comment]
@otakupahp 

no worries, you will have these exact settings for each variation inside a variable subscription, exactly the same way it is for variable products.

**Comment by drazenbebic** [comment]
Hello @DanielBakovic @otakupahp @srcmkr @sebastienserre 

I just added the full functionality in the latest commit. The plugin also logs some relevant debug info during a subscription renewal. This additional logging is added via the `error_log()` function and will be removed in production.

If anyone wants to test the plugin out, here's the link:

[license-manager-for-woocommerce.zip](https://github.com/drazenbebic/license-manager-for-woocommerce/files/5359594/license-manager-for-woocommerce.zip)

Let me know what you think :)

**Comment by otakupahp** [comment]
Please give me a few days to check it

**Comment by tony-defa** [comment]
Hello @drazenbebic 

the new options are all working as intended after the product has been saved. I did notice a bug while editing a variable subscription (issue #132). 

There is a little annoyance when tring to save a new subscription product. I've mentioned and fixed this in the pull request #129.

**Comment by drazenbebic** [comment]
@srcmkr @otakupahp @DanielBakovic @tony-defa 

Feature is done and merged into develop. Commit f499307d32e638ae6732211c89e9216f2757eb80

Thanks to everyone who helped. 

@tony-defa I took a look at your solution, but I think I found a better one by rewriting the layout of the WooCommerce Data Panel for variable products.

**Comment by vasikgreif** [comment]
@drazenbebic  This looks great, I wanted to try it, but wasn't able to save the product with the plugin updated (development branch). Is this a known bug?
