### ISSUE TITLE
Option group disapears in variable subscription

### ISSUE THREAD

**Issue by tony-defa** [drazenbebic/license-manager-for-woocommerce#132]
**Describe the bug**
If an attribute is modified on a variable subscription the License Manager for WooCommerce option group disapears.

**To Reproduce**
1. Create a variable subscription product with active variations or edit an existing variable subscription
2. Go to the attributes tab and modify the attribute
3. Go to the variations tab and open an existing variation
4. Notice the missing option group

**Expected behavior**
The option group shoud not disapper.

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser Firefox
 - Version 81.0.2

**Additional context**
The option group reappers if the page is reloaded.

**Comment by drazenbebic** [comment]
@tony-defa 

Definitely a bug, any idea how to fix? Working on it as we speak.

**Comment by drazenbebic** [comment]
@tony-defa found and fixed it in 55c2c746196d111948cff23180a3df927a91f60d

Will be included in the next update. This is closed.

**Comment by tony-defa** [comment]
@drazenbebic 

Great. I'll see if I can test the fix on monday.

**Comment by tony-defa** [comment]
@drazenbebic 

I can confirm the issue has been fixed
