### ISSUE TITLE
License Key state doesn't change after activation/deactivation

### ISSUE THREAD

**Issue by Mauricevb** [drazenbebic/license-manager-for-woocommerce#133]
**Describe the bug**
When activating or deactivating a license key using the API, the license state stays "delivered". I would expect the license key state to be "activate" when activated or "inactive" when deactivated and `timesActivated == 0`.

**To Reproduce**
1. Add a license key, state is now "Delivered"
2. Activate license key using API call `/wp-json/lmfwc/v2/licenses/activate/{{KEY}}`

**Expected behavior**
License key state should now be 'Active'.

**Comment by Mauricevb** [comment]
Oops, I missed #59

**Comment by drazenbebic** [comment]
No problem, I'll be closing this :)
