### ISSUE TITLE
Allow extending a licence once expired from My Account

### ISSUE THREAD

**Issue by gdarko** [drazenbebic/license-manager-for-woocommerce#135]
**Is your feature request related to a problem? Please describe.**
Imagine a scenario where you sold N amount of licences, now they are expired after certain period and the user simply wants to extend it. Is it possible to do that in the My Account area?

**Describe the solution you'd like**
Perfect solution from UX standpoint will be to go to My Account > Licences  and add a button that will redirect to the checkout page that says "Extend" once completed it bumps the expiry date of the licence depending on the length.

**Describe alternatives you've considered**
I haven't considered alternatives yet. Maybe switching to subscriptions but for existing keys this will be painful process.

Note: I am open to contribute if we find a feasible way to do this.

**Comment by drazenbebic** [comment]
Hello @gdarko 

I think that it's best to use WooCommerce Subscriptions for this. I've also just added support for it and it will be available in the next release.
