### ISSUE TITLE
Paid subscription for support

### ISSUE THREAD

**Issue by rvald26** [drazenbebic/license-manager-for-woocommerce#137]
Thank you for an awesome plugin.

We have started using it a lot, and I was wondering if you guys offer a paid subscription that my company could use to obtain priority support.

Thank you and best regards,

**Comment by drazenbebic** [comment]
Hello @rvald26 @maxi07

Not at the moment, no.

But, I'm currently working on a much more advanced licensing system. Email me at support@licensemanager.at if you're interested and we can work something out.
