### ISSUE TITLE
Generate License Key using Genrators

### ISSUE THREAD

**Issue by mhore22** [drazenbebic/license-manager-for-woocommerce#138]
**Is your feature request related to a problem? 
I'm using the REST API to generate a license key. But what I need is, I want to generate a license key using a Generator without passing the license key to be generated.

**Describe the solution you'd like**
A REST API call that will generate a license key using a generator.

**Comment by drazenbebic** [comment]
@mhore22 

Thank you for the suggestion. Makes sense, will be added!

**Comment by drazenbebic** [comment]
Added in 21c33a5a2c96473eb0aff1213177bbf42c83686e

Closed.
