### ISSUE TITLE
Critical WordPress Error when Trying to edit a License Generator

### ISSUE THREAD

**Issue by alex-drocks** [drazenbebic/license-manager-for-woocommerce#140]
**Describe the bug**
Hello Dear Drazen,
I just tried to edit my generators and WordPress has thrown an unhandled critical error.

**To Reproduce**
1. Go to License Manager Generators menu tab.
2. Click on "Edit" on one of your existing generators
4. See error bellow sent by WordPress to my email after getting the critical error warning page:

> Une erreur de type E_ERROR a été causée dans la ligne 20 du fichier /home/financed/magasin.finance-d.com/wp-content/plugins/license-manager-for-woocommerce/templates/generators/page-edit.php. Message d’erreur : Uncaught Error: Call to a member function get_id() on bool in /home/financed/magasin.finance-d.com/wp-content/plugins/license-manager-for-woocommerce/templates/generators/page-edit.php:20
Stack trace:
#0 /home/financed/magasin.finance-d.com/wp-content/plugins/license-manager-for-woocommerce/templates/page-generators.php(12): include_once()
#1 /home/financed/magasin.finance-d.com/wp-content/plugins/license-manager-for-woocommerce/includes/AdminMenus.php(277): include('/home/financed/...')
#2 /home/financed/magasin.finance-d.com/wp-includes/class-wp-hook.php(287): LicenseManagerForWooCommerce\AdminMenus->generatorsPage('')
#3 /home/financed/magasin.finance-d.com/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /home/financed/magasin.finance-d.com/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /home/financed/magasin.finance-d.com/wp-admin/admin.php(259): do_action('license-manager...')
#6 {main}
  thrown

**Expected behavior**
Normally it should show the window to edit the generator like it was working before (I don't know when it started to break
but today was the first time).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest

**Additional context**
WordPress Version: 5.5.3
Site language: fr-CA
Dashboard language: en_US
WooCommerce version: 4.7.0
License Manager Plugin version: 2.2.1
Number of generators in my account: 2
Specificities of my generators: both are identical execept that one of the two have a 90days expiration date and the otehr has no expiration.

Thanks in advance! :)

**Comment by drazenbebic** [comment]
Hello @alex-drocks 

seems to me like that generator was assigned to a product which has since been deleted. When editing a generator you can see a list of products at the bottom of the page, and this is what is causing the issue.

Do you maybe know the product ID of the product which has been deleted?

**Comment by alex-drocks** [comment]
Thanks @drazenbebic 

In the generators page, I do see that the 2 of my generators have a icon indicating that each of them is used on 2 products, but in reality they are only used by a single product right now. So you are right.

One generator is used by product ID 138 and the other is used by product ID 473.
These are my only two products but in my testing phase I probably had another one which I deleted.
Sadly I don't remember anything else.

Is there a way I could fix that manually in my database or that would be too risky ? (I'm very very bad with mySql).

**Comment by drazenbebic** [comment]
@alex-drocks 

Your safest bet for now would be to create a new generator and just delete the old one. I'll mark this as a bug.

**Comment by drazenbebic** [comment]
Fixed in 546c2116e27a89a38a5be6df1ff85b82c519a424

This is closed.
