### ISSUE TITLE
License Name Field

### ISSUE THREAD

**Issue by AndrejHronco** [drazenbebic/license-manager-for-woocommerce#144]
It would be really useful to be able to add a name to a license.

**Comment by drazenbebic** [comment]
@AndrejHronco 

Thank you for the suggestion. What's the use-case behind this? What would the name be used for?

**Comment by AndrejHronco** [comment]
I have a site where we offer 3rd party software licenses for use with our physical products (MIDI controllers) and some products have multiple software licenses available for the same product. I'm currently manually adding the database column with the software name and using that name to get the license in my query. it's working well, but it would be nice to be able to add the license name in the admin and with csv import.

Enjoying using your plugin as a developer. the plugin functions you have are easy to understand and very useful.

**Comment by drazenbebic** [comment]
@AndrejHronco Sorry but I don't think that this is something that will be featured in the plugin, at least not now.
