### ISSUE TITLE
Ability to change "License Keys" to "Gift Codes" or other arbitrary strings

### ISSUE THREAD

**Issue by dchote** [drazenbebic/license-manager-for-woocommerce#149]
This plugin is a good fit for gift codes, but the verbiage around License Keys leads to a little confusion. It would be great if we could expose a setting to allow an arbitrary term to be used.

**Comment by drazenbebic** [comment]
Hi @dchote 

This is already possible, but will be even easier in the next update. Take a look at commit 0287a6e4cf51b4875a75b769cc843af6223b6688

You can now edit the endpoint slug from WooCommerce Settings - Advanced, scroll down to "Account endpoints" and there you go:

![image](https://user-images.githubusercontent.com/26099016/106365388-963e1680-6335-11eb-841b-ab62b9b5c04f.png)

To change the page title and menu item label, use the following two filters:
`woocommerce_account_menu_items`
`woocommerce_endpoint_licenses_title`

This functionality will be a part of the next update coming very soon.

**Comment by dchote** [comment]
Great news! Thanks
