### ISSUE TITLE
2-step verification

### ISSUE THREAD

**Issue by jakrson** [drazenbebic/license-manager-for-woocommerce#150]
Hi, 
Thanks so much for great plugin
Can 2-step verification be enabled for show keys ? (for admin , customer , edit field,etc) .
Also, setting a time limit for display, for example, after each 2-step activation for up to 10 minutes, the keys can be viewed.

**Comment by drazenbebic** [comment]
Hello @jakrson 

I don't think that this is something that the plugin needs at the moment. Sorry.
