### ISSUE TITLE
Allow Assigning License without order

### ISSUE THREAD

**Issue by m42e** [drazenbebic/license-manager-for-woocommerce#153]
**Is your feature request related to a problem? Please describe.**
I have users which should receive a license key without placing an order.

**Describe the solution you'd like**
I want to be able to generate license keys and assign them to a user without having an order in place.

**Describe alternatives you've considered**
Creating a order manually is possible.

**Comment by drazenbebic** [comment]
Hello @m42e 

Good idea, I just can't wrap my head around the implementation and the workflow. I'm thinking of a custom email template, which you can edit/override from within WooCommerce. The question is, where do you select the license keys you want to send, and where do you select the customer to which to send the license keys to?

**Comment by m42e** [comment]
Just to be able to do this in the list view of the licenses would be enough. I would not event want to have it send out automatically.

**Comment by drazenbebic** [comment]
@m42e I was thinking about this some more, and I don't think that this will be part of the plugin functionality, at least not for now. Sorry.
