### ISSUE TITLE
How to add Subscription ID to API response

### ISSUE THREAD

**Issue by gkarmas** [drazenbebic/license-manager-for-woocommerce#155]
Wonderful job adding subscriptions on License Manager but can't figure out how to return the Subscription ID in the API response. 

This is a problem because when a subscription has being switched(upgraded/downgraded), I can see the subscription ID on license manager but I can't get the subscription ID with the API call.

On subscription switch, Order ID is being replaced with a new one, but the API returns the old Order ID.

What could be the best approach to do that?

**Comment by drazenbebic** [comment]
@gkarmas 

Added in 9985a8aaf9c5491752235830f26d27baf2326804

Will be included in the next update.

**Comment by cliqer** [comment]
Thanks for your work on this @drazenbebic but still subscription Ids are not getting returned yet, just an empty array.
