### ISSUE TITLE
How to get licence key when Order completed ( using Woocomerce )

### ISSUE THREAD

**Issue by keeloren** [drazenbebic/license-manager-for-woocommerce#156]
Hello, i am using Woocomerce plugin for my eCommerce website. And I am public API for mobile.

How to get license key when order status is complete from mobile.
I want to return the result with the license key attribute when updating the order with status complete

Thank you!

**Comment by drazenbebic** [comment]
Hi @keeloren 

For this, use the `lmfwc_event_post_order_license_keys` action. Here's a screenshot of the code / parameters:

![image](https://user-images.githubusercontent.com/26099016/106733441-2cae5880-6612-11eb-8913-a89962d8b79a.png)

`$orderId` is an integer
`$orderedLicenseKeys` is an array consisting of \LicenseManagerForWooCommerce\Models\Resources\License class objects. Class reference: https://github.com/drazenbebic/license-manager-for-woocommerce/blob/master/includes/models/resources/License.php

More about WordPress actions can be found here: https://developer.wordpress.org/plugins/hooks/actions/
