### ISSUE TITLE
List License Keys by Customer

### ISSUE THREAD

**Issue by m42e** [drazenbebic/license-manager-for-woocommerce#162]
I would like to receive license keys for a user using the userid.

**Describe the solution you'd like**
calling something like `v2/customer/<id>/licenses` to retrieve the license keys assigned to that customer, just like in the list all licenses.

**Describe alternatives you've considered**
Filtering on the other end would be extremly  ressource consuming.

Thanks

**Comment by Johnny99211** [comment]
Implemented in #173
