### ISSUE TITLE
[HELP WANTED] - High RAM usage on "Licenses" page / Unable to access "License" page

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#164]
Currently there is a number of plugin users who have troubles accessing the "Licenses" page. It either takes too long to load or doesn't load at all.

I've tried replicating the problem on my test server by importing a large number of licenses and orders, but to no avail. The licenses page loads just fine. Perhaps I haven't Imported enough orders or I don't have enough licenses, I really don't know.

I'm looking for help to solve this issue. This is particularly bad, because if the root issue really lies with the plugin, then it must be addressed and solved asap.

**Comment by drazenbebic** [comment]
@sebastienserre @tony-defa @Johnny99211 @otakupahp @DanielBakovic 

Pinging you guys in case anyone wants to take a look.

**Comment by otakupahp** [comment]
Can you access one of the sites with error? It would be great to know the site to find the possible culprit

**Comment by drazenbebic** [comment]
@otakupahp no, but I'm willing to give you and anyone else who's willing to help FTP and Database access to my test server. I'm currently looking for a way to import a large amount of dummy orders and customers to simulate a productive database.

**Comment by tony-defa** [comment]
Hey there, have not had the opportunity to test this, but did you try this to generate orders and users? 
https://github.com/75nineteen/order-simulator-woocommerce

**Comment by drazenbebic** [comment]
@tony-defa 

This plugin is exactly what I need right now! I'll make some test orders tomorrow and see what happens.

**Comment by tony-defa** [comment]
Good luck

**Comment by drazenbebic** [comment]
One user just reported that migrating hosts helped solve the issue. Now I'm almost certain that this is a server issue.

**Comment by otakupahp** [comment]
Good to know that you have it

**Comment by drazenbebic** [comment]
Fixed in c8b8c8a00c7a2bc0988a495ce856508d92cb5d99
