### ISSUE TITLE
Weiterentwicklung License Manager

### ISSUE THREAD

**Issue by Johnny99211** [drazenbebic/license-manager-for-woocommerce#169]
Hi Drazen,

ich hoffe, es geht dir soweit gut! Ich habe nun wieder etwas mehr Zeit mich deinem Lizenzmanager zu widmen. Gerne würde ich mich um folgende Themen kümmern:

- PHP 8.0 optimierung
- Generell einmal über den Code schauen und ein paar Dinge verbessern
- WC Subscriptions-Integration prüfen
- Meine Lizenzverwaltung rein mergen (hat sich jetzt mehrfach bewährt und läuft seit monaten einwandfrei bei mir)
- Eine neue Seite inkl. API Schnittstelle, welche anzeigt, auf welchem System Software X installiert ist
- Ein paar Issues abarbeiten

Wie findest du meinen Vorschlag und wie können wir hier zusammenarbeiten? In welchem Rahmen stehst du für Fragen zur Verfügung?

**Comment by drazenbebic** [comment]
Hallo @Johnny99211 

Sorry, war die letzten paar Tage bei meinen Eltern, daher keine Antwort. Generell hört sich das alles gut an. Ich will nun schon längere Zeit ein Update raus jagen, komme aber nicht dazu, daher ist jede Hilfe von immensem Wert.

* PHP 8.0 optimierung

Gerne, hört sich gut an!

* Generell einmal über den Code schauen und ein paar Dinge verbessern

Meinst du hiermit ein einfaches Refactoring?

* WC Subscriptions-Integration prüfen

Ja, unbedingt. Dieses Feature **muss** ins neue Update kommen.

* Meine Lizenzverwaltung rein mergen (hat sich jetzt mehrfach bewährt und läuft seit Monaten einwandfrei bei mir)

Meinst du damit die Produktupdates über den License Manager? Hatten wir doch schon gemacht? Sollte auf dem develop Branch sein.

* Eine neue Seite inkl. API Schnittstelle, welche anzeigt, auf welchem System Software X installiert ist

Das musst du mir noch ein bisschen erklären.

* Ein paar Issues abarbeiten

Ja :)

Also wenn dir wirklich danach ist, den License Manager weiterzuentwickeln, dann würde ich folgendes vorschlagen: Schreib mir doch bitte eine E-Mail mit deiner Telefonnummer, dann könnten wir uns besser besprechen und die nächsten Schritte festlegen. Alternativ dazu können wir auch hier oder per E-Mail kommunizieren.

**Comment by Johnny99211** [comment]
<info@bebic.at>: host mx01.ionos.de[217.72.192.67] said: 550 Requested action
not taken: mailbox unavailable (in reply to RCPT TO command)

Wollte dir eben meine Nummer senden..

**Comment by drazenbebic** [comment]
@Johnny99211 bitte an support@licensemanager.at senden :)
