### ISSUE TITLE
Add a fallback for license key font family

### ISSUE THREAD

**Issue by starypop** [drazenbebic/license-manager-for-woocommerce#3]
Hi!

If Consolas font, that is used for displaying license keys, is not installed on user's machine, browser uses an ugly default serif font.

![Zrzut ekranu 2019-04-19 o 12 23 51](https://user-images.githubusercontent.com/27000783/56420431-354b6880-629e-11e9-99a0-941a470fe403.png)

It can be fix easily by adding a 'monospace' fallback to CSS font-family values in main.css file in all cases in which we're using this font, such as: 

`font-family: "Consolas", monospace;`

Anyway, thanks for your fantastic work and such a great plugin!

**Comment by drazenbebic** [comment]
Hello @starypop,

I'm very sorry for the late reply, I wasn't receiving email notifications for new issues.

This is an oversight on my part and also an easy fix. I'll add it to the upcoming 1.3 release.

**Comment by drazenbebic** [comment]
Fixed in b0348cd3c0d43da5814c14b059fcfdef37b0cf1d
