### ISSUE TITLE
Deliver license when order set to processing

### ISSUE THREAD

**Issue by BlueHoundInc** [drazenbebic/license-manager-for-woocommerce#4]
Great plugin so far!

It would be nice if we had the option to have the license keys delivered when payment is complete and the order is set to processing. That way the customers get their key immediately but we don't have to mark it complete before we ship a physical part of an order.

Thanks for the good work!

**Comment by drazenbebic** [comment]
Hello @BlueHoundInc,

I'm very sorry about the late reply, I wasn't receiving email notifications for issues.

However it's not too late. I'll add this as a feature request and implement it in the upcoming 1.3 release.
