### ISSUE TITLE
How to submit domain address when activating the license key?

### ISSUE THREAD

**Issue by nabeghe** [drazenbebic/license-manager-for-woocommerce#41]
how to send domain address to 'v2/licenses/activate/{license_key}' route?!

**Comment by drazenbebic** [comment]
@nabeghe,

If I understand correctly, you wish to verify the domain from where the license key is being activated from?

If that is so, then I must let you know that this is not possible at the moment. I do plan to add this feature in a future release.

Please correct me if I misunderstood anything.

**Comment by drazenbebic** [comment]
Also, this is a duplicate of #21 

Please ask any and all questions there.
