### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by otakupahp** [drazenbebic/license-manager-for-woocommerce#42]
I run a PHP compatibility test over my site plugins and found some errors and warnings in the report

***********************************
FILE: /otakupahp/wp-content/plugins/license-manager-for-woocommerce/includes/Exception.php
---------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------
 9 | ERROR | The interface Throwable cannot be implemented directly, extend the Exception class instead.
---------------------------------------------------------------------------------------------------------

FILE: /otakupahp/wp-content/plugins/license-manager-for-woocommerce/vendor/defuse/php-encryption/src/Core.php
---------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 2 LINES
---------------------------------------------------------------------------------------------------------------------------
 282 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 282 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 308 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 308 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
---------------------------------------------------------------------------------------------------------------------------

FILE: /otakupahp/wp-content/plugins/license-manager-for-woocommerce/vendor/setasign/fpdf/makefont/makefont.php
----------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------
 388 | ERROR | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
----------------------------------------------------------------------------------------------------------------------------

FILE: /otakupahp/wp-content/plugins/license-manager-for-woocommerce/vendor/setasign/fpdf/fpdf.php
---------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
---------------------------------------------------------------------------------------------------------------
 1040 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 1044 | ERROR   | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
---------------------------------------------------------------------------------------------------------------

************************************************

Many of them are because of external libraries but they could create error in future environments.

**Comment by drazenbebic** [comment]
Hello @otakupahp,

I will see to it that I update the composer dependencies for the next release, hopefully the authors have fixed these PHP 7.3 incompatibilities.

The only incompatibility which is directly related to my code is the "Exception" class, which has already been removed from the plugin.
