### ISSUE TITLE
License Key header in order emails

### ISSUE THREAD

**Issue by BlueHoundInc** [drazenbebic/license-manager-for-woocommerce#5]
Our outbound order emails have been including the "License Key" section even though no keys were involved in the purchase.

**Comment by drazenbebic** [comment]
Hello @BlueHoundInc,

First I would like to apologize for the delayed answer. I wasn't receiving email notifications for new issues.

Now to the issue itself: This has already been reported in the WordPress support forum and will be fixed in the upcoming version.

**Comment by sissibieber** [comment]
seems not only in the email, but also on the order page(s) - header is shown eventhough there was no key sold with the order. 
(using version 1.2.4)

**Comment by drazenbebic** [comment]
@sissibieber,

that is true. It uses the same template, this will both be fixed in the upcoming 1.3 release.

**Comment by sissibieber** [comment]
great news. On a different note - it would be great if the template could be overwritten if there is a copy in the themes folder (like woocommerce template files) ... but that just might be a "nice to have".

**Comment by drazenbebic** [comment]
@sissibieber,

that's a great idea. I'll add it as a feature request and will implement it in the future. Possibly not in the next release, but will definitely do it.

**Comment by drazenbebic** [comment]
Fixed in b0348cd3c0d43da5814c14b059fcfdef37b0cf1d
