### ISSUE TITLE
Unlimited Activations

### ISSUE THREAD

**Issue by otakupahp** [drazenbebic/license-manager-for-woocommerce#50]
I would like to have a generator with "Unlimited Activations", maybe using the 0 as a configuration. Currently leaving the filed blank deactivates the API (or at least that is what the help text says). Although leaving the option blank will also be good option

**Comment by drazenbebic** [comment]
@otakupahp 

I will implement it so, that leaving the "Maximum activation count" blank results as unlimited activations. This will be part of the coming 2.2 update.

**Comment by otakupahp** [comment]
Great! thanks

**Comment by drazenbebic** [comment]
@otakupahp No problem!

I'll close the issue when the commit is done.
