### ISSUE TITLE
Option to move cryptographic secrets to wp-config.php

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#7]
The cryptographic secrets used by the plugin are stored in two text files inside a folder created by the plugin inside the `wp-content/uploads` folder. The plugin also automatically creates a `.htaccess` file to block direct access to the folder. This however does not work with `nginx` and could expose the cryptographic secrets to the public, presenting a security risk.

The user should be able to move the cryptographic secrets to the `wp-config.php` by creating two new constants with the contents of the defuse.txt and secret.txt. If these constants exist, the plugin will use them instead of accessing the files.

**Comment by drazenbebic** [comment]
Added in b0348cd3c0d43da5814c14b059fcfdef37b0cf1d

**Comment by alex-drocks** [comment]
Hey @drazenbebic hope you are well today, 

In the same sense of this #7 issue, how could I do the same thing for my REST API consumer key and secret? I am a very bad php coder I only know JavaScript and the concept of saving secure credentials to me is obscure. So I had to hardcode my credentials in a constants.php file which is probably a bad practice. 

I try to add them to the wp-config but I dont know how to use those constant in my REST API functions.

Could you please tell me if its possible to do in the current state of the extension and if so where would I start?

Thanks in advance 
Alex
