### ISSUE TITLE
Documentation and one Feature request

### ISSUE THREAD

**Issue by DanielBakovic** [drazenbebic/license-manager-for-woocommerce#85]
Hi,

I have a documentation and a feature request that will help us to use your pugin on our productive sites:

## API Documentation for Plugins and Themes
We sell WordPress plugins and themes. I miss a tutorial or a demo script how to integrate the license verification with plugins/themes (products). 

The user has to enter a license key and the product needs to check if it is valid or not. I didn't find a documentation about that on your website.

e.g https://docs.easydigitaldownloads.com/article/384-software-licensing-api

## One-click updates for WordPress plugins and themes

Your plugin could also serve updates for WordPress plugins and themes. Users with valid license will be able to upgrade and for others we could display a notice that they need to renew their license.

e.g. https://easydigitaldownloads.com/downloads/software-licensing/

👍 Thx

Best regards,
Daniel

**Comment by otakupahp** [comment]
I am using this plugin https://github.com/YahnisElsts/plugin-update-checker. I was thinking about preparing a pull request to add that

**Comment by drazenbebic** [comment]
@DanielBakovic 

thank you for your valuable input!

I have actually wanted to do a couple of tutorials and how-to's to cover some of the use-cases you mentioned. Currently I'm tied up with the 2.2.0 update, but after that's done I will show some love to the website and update the documentation.

I also like the idea about the integration into the plugin/theme update process. I haven't done anything like that at the moment, but I'll try to set up a demo plugin which needs a license to update from a third-party vendor.

All in all, great suggestions, will do! I just wish there were more hours in a day :)

**Comment by DanielBakovic** [comment]
Hi,

any news on this? ;)

**Comment by drazenbebic** [comment]
@DanielBakovic @otakupahp @sebastienserre 

Good news, thanks to @Johnny99211 and his PR, you will be able to handle this natively. Check this out here: https://github.com/drazenbebic/license-manager-for-woocommerce/pull/143

It'll be part of the next update coming before Christmas (I hope). I will update the documentation on the website accordingly.

**Comment by DanielBakovic** [comment]
Awesome thx!
