### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Mat-Hatter** [drazenbebic/license-manager-for-woocommerce#98]
Hello, firstly please let me say great plugin. We have just finished adapting it to work for our Unreal engine game project. I was wondering if it would be possible to add a section to the validate api which tells you which product the key is for.

**Comment by drazenbebic** [comment]
Hello @madmaty 

Thank you for your message and for using my plugin!

Yeah, definitely. I could add more data to the validate endpoint as you suggested. The response currently looks like this:

`{
    "success": true,
    "data": {
        "timesActivated": 0,
        "timesActivatedMax": 1,
        "remainingActivations": 1
    }
}`

I would suggest something like this:

`{
    "success": true,
    "data": {
        "timesActivated": 0,
        "timesActivatedMax": 1,
        "remainingActivations": 1,
        "product": {
        	"id": 123,
        	"sku": "PROD123",
        	"name": "Product 123"
        }
    }
}`

Would that work for you? 

PS: Is the game publicly available? Do you guys have a website? I'd like to take a look :)

**Comment by madmaty** [comment]
Yes, this would be perfect. Thank you so much for your speedy response. I am very impressed by your customer support :)

**Comment by daveboulden** [comment]
I would like to see this feature also.

**Comment by Johnny99211** [comment]
Added in #174
